### ISSUE TITLE
awake cronをGitHub Actionsに移行したい

### ISSUE THREAD

**Issue by uehr** [kitsystemyou/discordBot#40]

**Comment by kitsystemyou** [comment]
Try to Fix in 
d716ceeb54ee227ad54ef26f0fe906ecb08265d7 ~ 8798b4491336c06050169cd8210be813aaac5ee3
but curl job has been executed per (about) ~~15~~ 30 minutes ...

**Comment by kitsystemyou** [comment]
Github Actoins does'nt work well, so we should user alternative tools.
Close
